
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: bajrix-marketplace

  profiles:
    active: postgres

logging:
  level:
    com.bajrix.marketplace: INFO
    org.hibernate.SQL: WARN